### ISSUE TITLE
Getting Access Denied for deploy

### ISSUE THREAD

**Issue by akshar07** [brianleroux/arc-example-serverlessside-render-react#1]
Steps- 
1) npm run create 
this gives me : 

successfully deployed
https://nx54pfxi76.execute-api.us-east-2.amazonaws.com/staging
https://e2b6s6zbk8.execute-api.us-east-2.amazonaws.com/production

2) npm run deploy 
Success! Deployed 6 Lambdas in 5.456s
-------------------------------------
src/html/get-index ......... parcel-arc-staging-get-index ......... 0.14 mb
src/html/get-login ......... parcel-arc-staging-get-login ......... 0.14 mb
src/html/post-login ........ parcel-arc-staging-post-login ........ 0.14 mb
src/html/post-logout ....... parcel-arc-staging-post-logout ....... 0.14 mb
src/json/post-api-login .... parcel-arc-staging-post-api-login .... 0.14 mb
src/json/post-api-logout ... parcel-arc-staging-post-api-logout ... 0.14 mb

https://nx54pfxi76.execute-api.us-east-2.amazonaws.com/staging
Success! Deployed .static

But after this, I am getting access denied : 
  message: 'Access Denied',
  code: 'AccessDenied',
  region: null,
  time: 2018-02-23T18:21:40.689Z,
  requestId: '3C5004327D459F56',
  extendedRequestId: 'vQUImAPCW/unHmYDZfbwh/P5WZrcppQKTQz1C7f51WRobmr4WoWAMxV+QgIXiOVa2Y319z3ILwY=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 36.93347598777279 }

Is it an issue with my IAM ?

**Comment by brianleroux** [comment]
def an IAM issue / arc currently requires admin access! lmk if that helps

**Comment by akshar07** [comment]
I am still getting the same error. I have admin access and amazon s3 full access policies attached to the user.  Also, I do not see 2 buckets (staging and production) after running npm run create although I get success message and with urls.

**Comment by brianleroux** [comment]
something like this _should_ work!

<img width="271" alt="screen shot 2018-02-24 at 9 25 16 am" src="https://user-images.githubusercontent.com/990/36633131-c90b26ae-1944-11e8-9400-76741970553c.png">

**Comment by brianleroux** [comment]
oh!!! I realized that you are probably trying to create the buckets with the same names as in the repo but buckets in s3 are global! you'll need to change `.arc` with new names for the buckets! 

something like this:

```
@app
parcel-arc

@static
staging parcel-test-staging-1
production parcel-test-production-1

# defines some basic "server" routes
@html
get /
get /login
post /logout
post /login

@json
post /api/login
post /api/logout
```

**Comment by akshar07** [comment]
Yes that was it. Thanks

**Comment by brianleroux** [comment]
haha! nice. will be incorporating this learning into the companion blog post so thx for helping me improve it 🙇‍♂️
